Watching for file changes with StatReloader
HTTP GET / 200 [0.08, 172.18.0.5:43022]
HTTP GET /api/get_friends/ 200 [0.08, 172.18.0.5:43048]
HTTP GET /api/get_friend_requests/ 200 [0.09, 172.18.0.5:43034]
Not Found: /apple-touch-icon-precomposed.png
HTTP GET /apple-touch-icon-precomposed.png 404 [0.06, 172.18.0.5:43060]
Not Found: /apple-touch-icon.png
HTTP GET /apple-touch-icon.png 404 [0.06, 172.18.0.5:43062]
HTTP GET /api/get_friends/ 200 [0.04, 172.18.0.5:43076]
HTTP GET /api/get_friend_requests/ 200 [0.05, 172.18.0.5:43084]
HTTP GET /api/get_friends/ 200 [0.16, 172.18.0.5:56082]
HTTP GET /api/get_friend_requests/ 200 [0.17, 172.18.0.5:56066]
HTTP GET /api/get_friend_requests/ 200 [0.19, 172.18.0.5:56094]
HTTP GET /api/get_friends/ 200 [0.21, 172.18.0.5:56088]
HTTP GET /api/get_friend_requests/ 200 [0.10, 172.18.0.5:56112]
HTTP GET /api/get_friends/ 200 [0.13, 172.18.0.5:56102]
HTTP GET /api/get_friend_requests/ 200 [0.10, 172.18.0.5:56138]
HTTP GET /api/get_friends/ 200 [0.15, 172.18.0.5:56122]
HTTP GET /api/get_friend_requests/ 200 [0.07, 172.18.0.5:56156]
HTTP GET /api/get_friends/ 200 [0.08, 172.18.0.5:56152]
HTTP GET /api/get_friends/ 200 [0.12, 172.18.0.5:56168]
HTTP GET /api/get_friend_requests/ 200 [0.14, 172.18.0.5:56172]
HTTP GET /api/get_friend_requests/ 200 [0.10, 172.18.0.5:56186]
HTTP GET /api/get_friends/ 200 [0.11, 172.18.0.5:56178]
HTTP GET /api/get_friend_requests/ 200 [0.14, 172.18.0.5:58592]
HTTP GET /api/get_friends/ 200 [0.21, 172.18.0.5:58588]
HTTP GET /api/get_friend_requests/ 200 [0.09, 172.18.0.5:58620]
HTTP GET /api/get_friends/ 200 [0.12, 172.18.0.5:58604]
HTTP GET /api/get_friend_requests/ 200 [0.06, 172.18.0.5:58642]
HTTP GET /api/get_friends/ 200 [0.07, 172.18.0.5:58636]
HTTP GET /api/get_friend_requests/ 200 [0.11, 172.18.0.5:58646]
HTTP GET /api/get_friends/ 200 [0.12, 172.18.0.5:58652]
Method Not Allowed: /api/get_friends/
HTTP GET /api/get_friends/ 405 [0.14, 172.18.0.5:58662]
Internal Server Error: /api/get_friend_requests/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 516, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 516, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 520, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/hello_django/views.py", line 349, in get_friend_requests
    friend_requests = Friendship.objects.filter(to_user=user, accepted=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1480, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1307, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd49d46b950>>.
HTTP GET /api/get_friend_requests/ 500 [0.87, 172.18.0.5:58658]
Method Not Allowed: /api/get_friends/
HTTP GET /api/get_friends/ 405 [0.12, 172.18.0.5:58676]
Method Not Allowed: /api/get_friends/
HTTP GET /api/get_friends/ 405 [0.05, 172.18.0.5:58688]
Internal Server Error: /api/get_friend_requests/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2053, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 516, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 516, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 468, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asgiref/sync.py", line 520, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/hello_django/views.py", line 349, in get_friend_requests
    friend_requests = Friendship.objects.filter(to_user=user, accepted=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1480, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1307, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7fd49dd11fd0>>.
HTTP GET / 200 [0.50, 172.18.0.5:44882]
HTTP GET /login/ 200 [0.08, 172.18.0.5:44888]
HTTP GET /connexion_42/?csrfmiddlewaretoken=yaMxadO0zLUtJ6IENo8nDxY0WYzX7bhHDCfy2TSEELm5GMhzTkHVOnUK3NmNDRBn 302 [0.05, 172.18.0.5:44904]
HTTP GET /redirection_apres_authentification?code=3899ecfed75a1b668c6121e176a7efd345f8e222354ca487580d0def4bd0ca94 301 [0.11, 172.18.0.5:44906]
HTTP GET /redirection_apres_authentification/?code=3899ecfed75a1b668c6121e176a7efd345f8e222354ca487580d0def4bd0ca94 302 [0.02, 172.18.0.5:44910]
HTTP GET /exchange_code_for_access_token/3899ecfed75a1b668c6121e176a7efd345f8e222354ca487580d0def4bd0ca94/ 302 [0.28, 172.18.0.5:44920]
HTTP GET / 200 [0.02, 172.18.0.5:44930]
HTTP GET /login/ 200 [0.30, 172.18.0.5:55288]
HTTP GET /connexion_42/?csrfmiddlewaretoken=2lkHUbixvFNjD55ehhEQji6NlFxRsXdA7NNIMRmbAFfVALE9nddou82xsukHYDxg 302 [0.05, 172.18.0.5:55292]
HTTP GET /redirection_apres_authentification?code=42b4fc49ec0d8c64e371b72466916ae09859c7b2ee77d258822d86d3566398ba 301 [0.07, 172.18.0.5:55298]
HTTP GET /redirection_apres_authentification/?code=42b4fc49ec0d8c64e371b72466916ae09859c7b2ee77d258822d86d3566398ba 302 [0.02, 172.18.0.5:55300]
HTTP GET /exchange_code_for_access_token/42b4fc49ec0d8c64e371b72466916ae09859c7b2ee77d258822d86d3566398ba/ 302 [0.19, 172.18.0.5:55310]
HTTP GET / 200 [0.03, 172.18.0.5:55312]
/usr/src/app/hello_django/views.py changed, reloading.
Watching for file changes with StatReloader
HTTP GET /login/ 200 [0.05, 172.18.0.5:57296]
HTTP GET / 200 [0.02, 172.18.0.5:38148]
HTTP GET /login/ 200 [0.02, 172.18.0.5:38152]
HTTP GET /connexion_42/?csrfmiddlewaretoken=I12Pi8MKyrEzfxsiOEmDB1R7VYLfj6DtNtvQaOQoDr6bcd1dUAVbMRNR2Ny5PMX9 302 [0.03, 172.18.0.5:38156]
HTTP GET /redirection_apres_authentification?code=28d2d2420faaf6682a7350301344d2a77ab87970722c2af2e6d0063961a24f32 301 [0.05, 172.18.0.5:38158]
HTTP GET /redirection_apres_authentification/?code=28d2d2420faaf6682a7350301344d2a77ab87970722c2af2e6d0063961a24f32 302 [0.02, 172.18.0.5:38164]
HTTP GET /exchange_code_for_access_token/28d2d2420faaf6682a7350301344d2a77ab87970722c2af2e6d0063961a24f32/ 302 [0.33, 172.18.0.5:38172]
HTTP GET / 200 [0.03, 172.18.0.5:38188]
